asamuzaK/sidebarTabs

src/_locales/en/messages.json, src/_locales/ja/messages.json, src/html/sidebar.html, src/js/contextmenu.js, src/js/sidebar.js
=> Add accesskey support

src/_locales/en/messages.json, src/_locales/ja/messages.json, src/html/sidebar.html, src/js/sidebar.js
=> Add bookmark handler

src/js/sidebar.js
=> Refactor drag and drop

src/js/sidebar.js
=> Add put new tab at the end handler

src/js/sidebar.js
=> Select tabs with shift + click

src/js/sidebar.js
=> Add dropped link handler

src/mjs/sidebar.js
Fix #51
Caveats
* Can not be grouped
* Only droppable in sidebar
=> Ability to drag and drop tab(s) to other window

src/mjs/main.js
=> Add scrollIntoView

src/mjs/main.js, src/mjs/util.js, test/main.test.js, test/util.test.js
=> Refactor scroll tab into view

src/_locales/en/messages.json, src/_locales/ja/messages.json, src/html/options.html, src/mjs/constant.js, src/mjs/main.js, src/mjs/tab-group.js, test/main.test.js, test/tab-group.test.js
Fix #85 (option part), fix #84 
Also add fix for #83
=> Collapse other tab groups when expand a group

src/_locales/en/messages.json, src/_locales/ja/messages.json, src/html/options.html, src/manifest.json, src/mjs/browser.js, src/mjs/constant.js, src/mjs/main.js, src/mjs/options-main.js, src/mjs/util.js, test/browser.test.js, test/main.test.js, test/options-main.test.js, test/util.test.js
=> Add ability to close tab by double click

src/mjs/browser-tabs.js, test/browser-tabs.test.js
=> Check if array is not empty

src/_locales/en/messages.json, src/_locales/ja/messages.json, src/html/options.html, src/mjs/browser.js, src/mjs/constant.js, src/mjs/options-main.js, test/browser.test.js, test/options-main.test.js
=> Add option to show context menu on mouseup

.eslintrc, src/mjs/main.js, src/mjs/sidebar.js, test/main.test.js
Split  event handler functions and refactor
=> Complexity

src/_locales/en/messages.json, src/_locales/ja/messages.json, src/html/options.html, src/mjs/main.js, src/mjs/util.js, test/main.test.js, test/util.test.js
=> Switch tab by scrolling mouse wheel

src/mjs/main.js, src/mjs/tab-group.js, test/main.test.js
=> Fix tab on created handler

src/mjs/browser-tabs.js, src/mjs/main.js, test/browser-tabs.test.js
=> Do not include pinned tabs

src/mjs/main.js, test/main.test.js
=> Switch update menuItemID based on parentId

src/_locales/en/messages.json, src/_locales/ja/messages.json, src/mjs/main.js, src/mjs/menu-items.js, src/mjs/tab-content.js, test/main.test.js, test/tab-content.test.js
Close n tabs
Mute/Unmute n tabs
=> Show number of tabs in menu and tooltips

src/mjs/sidebar.js
=> Add 'url' to filter properties

src/_locales/de/messages.json, src/_locales/en/messages.json, src/_locales/ja/messages.json, src/html/options.html, src/mjs/constant.js, src/mjs/main.js, test/main.test.js
=> Add option to invert scroll direction

src/mjs/main.js, src/mjs/tab-dnd.js, test/main.test.js, test/tab-dnd.test.js
=> Improve dnd

src/mjs/main.js, src/mjs/tab-dnd.js, test/main.test.js, test/tab-dnd.test.js
=> Refactor dnd handling

src/_locales/de/messages.json, src/_locales/en/messages.json, src/_locales/ja/messages.json, src/html/options.html, src/mjs/constant.js, src/mjs/main.js, test/main.test.js
=> Add option to always switch tab with mouse wheel

src/mjs/main.js, test/main.test.js
=> Fix created tab and updated tab handling

src/mjs/main.js, src/mjs/tab-dnd.js, test/main.test.js, test/tab-dnd.test.js
=> Duplicate tab with Ctrl + drag

src/mjs/tab-dnd.js, test/tab-dnd.test.js
=> Fix moving tab group

resource/dark-manifest.json, src/html/options.html, src/mjs/constant.js, src/mjs/main.js, src/mjs/options-main.js, src/mjs/theme.js, test/main.test.js, test/options-main.test.js, test/theme.test.js
=> Store each custom theme values

src/_locales/de/messages.json, src/_locales/en/messages.json, src/_locales/ja/messages.json, src/html/options.html, src/html/sidebar.html, src/mjs/constant.js, src/mjs/main.js, src/mjs/tab-group.js, test/main.test.js, test/tab-group.test.js
=> Add option item to exclude pinned tabs

src/mjs/main.js
=> Make sure insert target exists

package.json, src/mjs/browser.js, src/mjs/constant.js, src/mjs/theme.js, test/theme.test.js
Fixed an issue caused by internal changes in Firefox
Ref [1748557 - management namespace persistent listeners](https://bugzilla.mozilla.org/show_bug.cgi?id=1748557)
=> Save ID of the current theme

src/mjs/main.js, src/mjs/menu.js, test/main.test.js, test/menu.test.js
=> Fix contextual identity handlers

src/mjs/util.js
=> Serialize document.doctype

package.json, src/mjs/main.js, src/mjs/tab-group.js, test/main.test.js, test/tab-group.test.js
=> Activate collapsed tab only if tab group contains highlighted tab(s) 

src/_locales/fa/messages.json
Thanks for this amazing add-on.
What are "Dicarded Tab" and "Selected Tab" (in the Custom Theme section)? How can I find them in Firefox?
Some strings are untranslated because I couldn't find the place they're being used.
=> Persian translation

src/mjs/main.js, src/mjs/theme.js, test/theme.test.js
Follow up for #208
Partially fixes #207
=> Refactoring of functions to support temporarily applied dynamic theme

src/mjs/theme.js, test/theme.test.js
=> Support local theme on restart

src/mjs/main.js, test/main.test.js
=> Append child if insert target previous sibling is group container

src/mjs/color.js, test/color.test.js, test/theme.test.js
* Add currentColor support
* Convert colors through xyz instead of hex
* Optimize functions
=> Rewrite color.js

src/mjs/main.js, test/main.test.js
=> Fix restoreTabGroups function

modules/commander.js, test/commander.test.js
=> Fetch resources from mozilla-central again

src/html/options.html, src/mjs/constant.js, src/mjs/options-main.js, src/mjs/theme.js, test/options-main.test.js, test/theme.test.js
=> Send color scheme of current theme

src/html/sidebar.html, src/mjs/constant.js, src/mjs/main.js, src/mjs/util.js, test/main.test.js, test/util.test.js
=> Add ability to resize pinned tabs container

src/mjs/main.js, test/main.test.js
=> Handle clicked menu only if the window is focused

src/manifest.json, src/mjs/background.js, src/mjs/menu-items.js
=> Migrate to MV3

package.json, src/mjs/browser-tabs.js, src/mjs/main.js
Additional test for https://github.com/dperini/nwsapi/issues/83
=> Add workarounds for nwsapi and remove overrides field

src/mjs/tab-dnd.js, test/tab-dnd.test.js
Fix #261
1. Select multiple tabs (or all tabs in the same group)
2. Shift + Alt + DnD (Shift + Option + DnD on Mac)
=> Group multiple tabs on DnD

src/mjs/main.js, test/main.test.js
=> Always include openerTabId

src/mjs/main.js, src/mjs/tab-content.js, src/mjs/util.js, test/tab-content.test.js, test/util.test.js
=> Add support for Facebook Container extenstion

src/_locales/ja/messages.json
=> Fix messages

src/mjs/tab-dnd.js, test/tab-dnd.test.js
=> Review dnd

src/_locales/fa/messages.json
=> Update Persian localization

src/mjs/tab-content.js
=> Use URL.hostname

src/mjs/tab-dnd.js, test/main.test.js, test/tab-dnd.test.js
=> Require altKey to enable drop outside sidebar

src/_locales/en/messages.json, src/_locales/fa/messages.json, src/_locales/ja/messages.json, src/mjs/menu-items.js
=> Update access keys and Japanese locale

src/mjs/browser-tabs.js, src/mjs/main.js, test/browser-tabs.test.js, test/main.test.js
=> Add handler for middle click on new tab button

resource/light-manifest.json, src/mjs/tab-dnd.js, src/mjs/tab-group.js, test/tab-dnd.test.js, test/tab-group.test.js
Partially fixes #335 (former bug part)
=> Expand collapsed tab group when tab is dropped

src/css/sidebar.css, src/mjs/main.js, src/mjs/tab-dnd.js, src/mjs/tab-group.js, test/tab-dnd.test.js, test/tab-group.test.js
=> let heading be a drop target
